---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sentry-kafka
  namespace: sentry
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      acks: all
      auto.offset.reset: latest
      cruise.control.metrics.topic.num.partitions: 10
      default.replication.factor: 2
      # inter.broker.protocol.version: "3.6"
      log.cleanup.policy: delete
      log.retention.bytes: 2147483648 # 2Gb * 1024 * 1024 * 1024
      log.retention.check.interval.ms: 300000
      log.retention.hours: 24
      log.segment.bytes: 104857600 # 100MB * 1024 * 1024
      message.max.bytes: 10485760 # 10MB * 1024 * 1024
      min.insync.replicas: 1
      num.io.threads: 64
      num.network.threads: 32
      num.partitions: 10
      num.recovery.threads.per.data.dir: 2
      num.replica.fetchers: 1
      offsets.topic.replication.factor: 2
      queued.max.requests: 500
      replica.fetch.max.bytes: 10485760
      replica.socket.receive.buffer.bytes: 65536
      sample.store.topic.replication.factor: 2
      socket.receive.buffer.bytes: 1048576
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 1048576
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 2
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi
    storage:
      type: persistent-claim
      class: yc-network-ssd
      size: 30Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
