---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: sentry-clickhouse  # Имя установки ClickHouse для Sentry
  namespace: sentry  # Пространство имен, в котором будет развернута установка
spec:
  reconciling:
    policy: wait  # Политика реконсиляции: ожидание завершения всех задач перед продолжением
  defaults:
    distributedDDL:
      profile: default  # Профиль для распределенных DDL операций
    templates:
      dataVolumeClaimTemplate: default  # Шаблон для запроса на выделение объема данных
      podTemplate: clickhouse  # Шаблон для конфигурации пода
      serviceTemplate: internal  # Шаблон для конфигурации сервиса
  configuration:
    settings:
      timezone: UTC  # Временная зона по умолчанию
      prometheus/endpoint: /metrics  # Конечная точка для сбора метрик Prometheus
      prometheus/port: 9363  # Порт для сбора метрик Prometheus
      prometheus/metrics: true  # Включение сбора метрик Prometheus
      prometheus/events: true  # Включение сбора событий Prometheus
      prometheus/asynchronous_metrics: true  # Включение сбора асинхронных метрик Prometheus
      prometheus/status_info: true  # Включение сбора информации о статусе Prometheus
      logger/level: warning  # Уровень логирования
      clickhouse/distributed_ddl/path: /clickhouse/task_queue/ddl  # Путь для распределенных DDL операций
      clickhouse/distributed_ddl/profile: default  # Профиль для распределенных DDL операций
      clickhouse/distributed_ddl/pool_size: 8  # Размер пула для распределенных DDL операций
    users:
      sentry/profile: default  # Профиль пользователя Sentry
      sentry/networks/ip:
        - "127.0.0.1"  # Локальный IP-адрес
        - "10.0.0.0/8"  # Сеть IP-адресов
      sentry/password_sha256_hex: "xxxxx"  # Хеш пароля пользователя Sentry
      sentry/quota: default  # Квота пользователя Sentry

    profiles:
      readonly/readonly: "2"  # Профиль только для чтения
      default/distributed_product_mode: "allow"  # Режим распределенных продуктов
    zookeeper:
      nodes:
        - host: zookeeper.zookeeper.svc.cluster.local  # Хост ZooKeeper
          port: 2181  # Порт ZooKeeper
    clusters:
      - name: sharded  # Имя кластера: chi-sentry-sharded-<x>-<x>-<x>
        secret:
          auto: "True"  # Автоматическое управление секретами
        layout:
          shardsCount: 3  # Количество шардов в кластере

  templates:
    serviceTemplates:
      - name: internal  # Имя шаблона сервиса
        generateName: "ch-{chi}"  # Генерируемое имя сервиса
        spec:
          ports:
            - name: http  # Порт для HTTP
              port: 8123
            - name: tcp  # Порт для TCP
              port: 9000
          type: ClusterIP  # Тип сервиса: ClusterIP
    volumeClaimTemplates:
      - name: default  # Имя шаблона запроса на выделение объема
        reclaimPolicy: Retain  # Политика восстановления: сохранение данных после удаления
        spec:
          storageClassName: yc-network-ssd  # Класс хранилища
          accessModes:
            - ReadWriteOnce  # Режим доступа: чтение-запись одним пользователем
          resources:
            requests:
              storage: 100Gi  # Запрошенный объем хранилища
    podTemplates:
      - name: clickhouse  # Имя шаблона пода
#        podDistribution:
#          - type: ReplicaAntiAffinity  # Анти-аффинити по репликам
#            topologyKey: "topology.kubernetes.io/zone"
#          - type: ShardAntiAffinity  # Анти-аффинити по шардам
#            topologyKey: "topology.kubernetes.io/zone"
#          - type: MaxNumberPerNode  # Максимальное количество подов на узле
#            number: 1
#            topologyKey: "kubernetes.io/hostname"
        spec:
          terminationGracePeriodSeconds: 3600  # Время ожидания перед принудительным завершением
          containers:
            - name: clickhouse  # Контейнер ClickHouse
              image: dockerhub.timeweb.cloud/clickhouse/clickhouse-server:23.3.8.21  # Имя образа
              lifecycle:
                preStop:
                  exec:
                    command:
                      - "/bin/bash"
                      - "-c"
                      - |
                        while [ "$(clickhouse-client --query 'SHOW PROCESSLIST')" ]; do
                          sleep 1
                        done  # Команда выполняемая перед остановкой контейнера
              resources:
                requests:
                  memory: 4Gi  # Запрошенная память
                  cpu: 1  # Запрошенные CPU
                limits:
                  memory: 4Gi  # Лимит памяти
                  cpu: 1  # Лимит CPU
              ports:
                - name: "metrics"  # Порт для метрик
                  containerPort: 9363
            - name: clickhouse-exporter  # Контейнер экспортера метрик ClickHouse
              image: dockerhub.timeweb.cloud/f1yegor/clickhouse-exporter:latest  # Имя образа
              env:
                - name: CLICKHOUSE_USER  # Переменная окружения для пользователя
                  value: sentry
                - name: CLICKHOUSE_PASSWORD  # Переменная окружения для пользователя
                  value: sentry-password
              resources:
                limits:
                  memory: 256Mi  # Лимит памяти
                  cpu: 200m  # Лимит CPU
                requests:
                  memory: 128Mi  # Запрошенная память
                  cpu: 100m  # Запрошенные CPU
              ports:
                - name: ch-metrics  # Порт для метрик экспортера
                  containerPort: 9116
