grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: ['grafana.apatsev.org.ru']
    path: "/"

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
